# The URL the site will be built for
base_url = "https://rocco.dev"

theme = "terminimal"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    {name = "tags"},
]

title = "RoccoDev"

[extra]
author = "RoccoDev"
github = "roccodev"
twitter = "RealRoccoDev"
logo_text = "RoccoDev"

accent_color = "green"
favicon = "/img/favicon.png"

menu_items = [
    {name = "about", url = "$BASE_URL"},
    {name = "blog", url = "$BASE_URL/posts"},
    {name = "projects", url = "$BASE_URL/projects"},
    {name = "xenoblade", url = "$BASE_URL/xenoblade"},
    {name = "contact", url = "$BASE_URL/contact"},
    {name = "code", url = "https://github.com/RoccoDev", newtab = true},
]

enable_post_view_navigation = true
post_view_navigation_prompt = "Read more"

[markdown.highlighting]
theme = "kanagawa-wave"
